config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "home#index"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:new, :create]
  get '/books', to: 'books#search'

  resources :tasks do
    collection do
      get 'today'
    end

    resources :reads, only: [:new, :create, :destroy]
  end
end

app/models/read.rb
class Read < ApplicationRecord
  belongs_to :task
  has_one :user, through: :task

  # バリデーション
  validates :read_on, presence: true
  validates :up_to_page, presence: true, numericality: { only_integer: true, greater_than: 0 }

  validate :validate_up_to_page_with_total_pages,
    :validate_up_to_page_with_saved_up_to_page,
    :validate_up_to_page_and_read_on

  def validate_up_to_page_with_total_pages
    if up_to_page.present? && up_to_page > task.book.total_pages
      errors.add(:up_to_page, ": 総ページ数より大きい数は登録できません")
    end
  end

  def validate_up_to_page_with_saved_up_to_page
    max_read_up_to_page = "Read".constantize.where(task_id: task.id).maximum(:up_to_page) || 0
    if up_to_page.present? && up_to_page <= max_read_up_to_page
      errors.add(:up_to_page, ": 登録済みのページ番号より小さい数は登録できません")
    end
  end

  def validate_up_to_page_and_read_on
    read = task.reads.order(up_to_page: :desc).order(read_on: :desc).limit(1)
    if read.present?
      max_read_up_to_page = read[0].up_to_page
      date_max_read_up_to_page = read[0].read_on
      if up_to_page.present? && read_on.present? && up_to_page > max_read_up_to_page && date_max_read_up_to_page > read_on
        errors.add(:up_to_page, ": すでに過去の日付でより大きいページ番号が登録されています")
      end
    end
  end

  # タスク一覧ページの SimpleCalendar で使用
  def start_time
    self.read_on
  end

  # 1ヶ月間の最大ページ、読んだページ、読んだ冊数を計算
  def self.cal_month_data(user, time)
    this_month_read = user.reads.where(read_on: time.all_month)
    if this_month_read.present?
      max_page = this_month_read.group(:task_id).maximum(:up_to_page)
      max_page_last = "Read".constantize.where(task_id: max_page.keys).where(read_on: time.advance(months: -1).all_month).group(:task_id).maximum(:up_to_page)

      if max_page_last.present?
        read_page = max_page.merge(max_page_last){|k, v1, v2| v1 - v2}
      else
        read_page = max_page
      end
      read_pages = read_page.values.inject(:+)

      # 読んだ冊数を計算
      tasks = Task.includes(:book).where(id: max_page.keys).pluck(:book_id)
      total_pages = Book.where(id: tasks).pluck(:total_pages)
      read_book = 0
      total_pages.zip(max_page.values) do |total_pages, max_page|
        total_pages == max_page ? read_book += 1 : read_book += 0
      end
    else
      max_page = 0
      read_pages = 0
      read_book = 0
    end

    # 1日あたりのページ数を計算
    month_days = [*Date.today.all_month].size
    day_pages = read_pages / month_days

    data = {
      read_pages: read_pages,
      read_book: read_book,
      day_pages: day_pages
    }
  end

  # 今月と先月の最大ページ、読んだページを準備
  def self.month_data(user)
    time = Time.now
    this_month_data = self.cal_month_data(user, time)

    time = Time.now.advance(months: -1)
    last_month_data = self.cal_month_data(user, time)

    month_data = {
      this_month: this_month_data,
      last_month: last_month_data
    }
    return month_data
  end

  def self.reads_percentage(reads, task)
    reads_percentage = {}
    if reads
      reads.reverse.each do |read|
          percentage = 100 * read.up_to_page / task.book.total_pages
          reads_percentage.store(
            read.read_on,
            percentage
          )
      end
    end
    return reads_percentage
  end
end

app/controllers/reads_controller.rb
class ReadsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task

  def new
    if params
      @read = Read.new(read_on: params[:read_on])
    else
      @read = Read.new
    end
    session[:previous_url] = request.referer
  end

  def create
    @read = @task.reads.build(read_params)
    if @read.save
      if session[:previous_url]
        redirect_to session[:previous_url], notice: "進捗を登録しました"
      else
        redirect_to today_tasks_path, notice: "進捗を登録しました"
      end
    else
      flash.now[:alert] = "進捗の登録に失敗しました。"
      render :new
    end
  end

  def destroy
    @read = @task.reads.find(params[:id])
    @read.destroy!
    redirect_to task_path(@task.id), alert: "削除しました"
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end

  def read_params
    params.require(:read).permit(:read_on, :up_to_page)
  end
end

app/views/reads/_form.html.erb
<div class="ReadForm">
  <div class="c-container">
    <%= render 'shared/page_bar', var: "", text: "読んだ日と読み終わったページ番号を設定" %>

    <div class="ReadForm__title"><%= task.book.title %></div>
    <div class="ReadForm__wrapper">
      <div class="ReadForm__data">
        <div class="ReadForm__book-image">
          <%= render 'books/book_image', image_link: task.book.image_link %>
        </div>
        <dl>
          <dt>ページ数</dt>
          <dd><%= task.book.total_pages %></dd>
        </dl>
      </div>

      <%= form_with model: [task, read], local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
        <div class="ReadForm__form">
          <%= f.label :read_on %>
          <%= f.date_field :read_on %>
        </div>
        <div class="ReadForm__form">
          <%= f.label :up_to_page, "読み終わった<br>ページ番号".html_safe %>
          <%= f.text_field :up_to_page %>
        </div>
        <div class="ReadForm__submit">
          <%= f.submit button_value %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reads/_index.html.erb
<div class="ReadIndex">
  <div class="ReadIndex__wrapper">
    <p>進捗データ</p>
    <div class="ReadIndex__border"></div>
    <%= area_chart reads_percentage, min: 0, max: 100 %>
    <%= link_to "新規登録", new_task_read_path(task), class: "--button" %>
  </div>
  <div class="ReadIndex__wrapper">
    <p>進捗一覧</p>
    <div class="ReadIndex__border"></div>
    <% if reads.present? %>
      <table class="--read" id="js-ReadIndex__table">
        <thead class="--read">
          <tr>
            <th class="--read">読んだ日</th>
            <th class="--read">読み終わった<br />ページ</th>
            <th></th>
          </tr>
        </thead>
        <tbody id="js-ReadIndex__reads">
          <%= render partial: "reads/read_data", locals: { task: task }, collection: reads, as: "read" %>
        </tbody>
      </table>
      <div class="ReadIndex__reads-more"><a href="#" id="js-ReadIndex__reads-more">more...</a></div>
    <% else %>
      <div class="ReadIndex__message">進捗がありません</div>
    <% end %>
  </div>
</div>

app/views/reads/_read_data.html.erb
<tr class="--read">
  <td class="--read"><%= read.read_on %></td>
  <td class="--read">p.<%= read.up_to_page %></td>
  <td class="--read">
    <%= link_to "削除", task_read_path(task, read), method: :delete, data: { confirm: "削除しますか?" } %>
  </td>
</tr>

app/views/reads/new.html.erb
<div class="ReadNew">
  <%= render 'shared/page_top', main: "Read", sub: "進捗の登録" %>
  <div class="c-container">
    <div class="Breadcrumbs">
      <%= link_to 'TOP', '/' %>
      <span class="--arrow">></span>
      <span class="--now">進捗の登録</span>
    </div>
  </div>

  <%= render "form", task: @task, read: @read, button_value: "登録" %>
</div>