config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "home#index"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:new, :create]
  get '/books', to: 'books#search'

  resources :tasks do
    collection do
      get 'today'
    end

    resources :reads, only: [:new, :create, :destroy]
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :book
  belongs_to :user
  has_many :reads, dependent: :destroy

  # バリデーション
  validates :started_on, presence: true
  validates :finished_on, presence: true
  validate :validate_finished_on

  def validate_finished_on
    if finished_on.present? && finished_on < started_on
      errors.add(:finished_on, ": 開始日より前の日付は使えません")
    end
  end

  # 進行中のタスク一覧(TaskTodayページ)
  def self.tasks_in_progress(tasks)
    tasks_in_progress = []
    max_reads = Task.includes(:reads).group(:task_id).maximum(:up_to_page)
    tasks.each do |task|
      max_reads[task.id].present? ? max_page = max_reads[task.id] : max_page = 0
      total_pages = task.book.total_pages
      if total_pages > max_page
        tasks_in_progress.push(task)
      end
    end
    return tasks_in_progress
  end

  # 残りページ数、今日の最大ページ数、最大ページ数
  def self.task_data(task)
    max_page_yesterday = task.reads.where("read_on < ?", Date.today).maximum(:up_to_page) || 0
    max_page_today = task.reads.where("read_on = ?", Date.today).maximum(:up_to_page) || 0
    max_page = [max_page_yesterday, max_page_today].max
    read_pages = task.book.total_pages - max_page_yesterday

    task_data = {
      read_pages: read_pages,
      max_page_today: max_page_today,
      max_page: max_page
    }
  end

  # 今日の目標ページ番号( 残りページ数/残り日数 )
  def self.today_goal_page(task, task_data)
    left_days = (task.finished_on - Date.today + 1).to_i
    left_days <= 0? left_days=0 : left_days
    left_days == 0? task_data[:read_pages] : (task_data[:read_pages] / left_days.to_f).ceil
  end

  # 今週の進捗登録がある日とない日
  def self.status_week(task)
    today = Date.today
    from = today.prev_occurring(:monday)
    to = today.next_occurring(:sunday)
    if today.wday == 1
      from = today
    elsif today.wday == 0
      to = today
    end

    reads = task.reads.select(:read_on).where(read_on: from..to)

    status_week = {}
    (from..to).each do |date|
      reads_date = reads.select{ |read|read.read_on == date}
      if reads_date.present?
        per = "--main"
      else
        per = nil
      end
      status_week.store(date.day, per)
    end
    return status_week
  end

  # 今日の目標のデータ(TaskTodayページ)
  def self.today_data(task)
    task_data = self.task_data(task)
    today_goal_page = self.today_goal_page(task, task_data)
    status_week = self.status_week(task)

    # 今日の目標達成ステータス
    if today_goal_page <= task_data[:max_page_today]
      status = { color: "main", status: "DONE"}
    else
      today_left_pages = today_goal_page - task_data[:max_page]
      status = { color: "second", status: "あと#{today_left_pages}ページ"}
    end

    today_data = {
      today_goal_page: today_goal_page,
      status: status,
      status_week: status_week
    }
    return today_data
  end

  # タスク進捗パーセンテージの計算
  def self.cal_percentage(task_percentage, max_page, total_pages)
    percentage = 100 * max_page / total_pages

    task_percentage.push(
      {
        read: percentage, unread: 100 - percentage
      }
    )
  end

  # タスクの進捗パーセンテージ(TaskIndaxページ)
  def self.tasks_percentage(tasks)
    tasks_percentage = []
    max_reads = Task.includes(:reads).group(:task_id).maximum(:up_to_page)

    tasks.each do |task|
      max_reads[task.id].present? ? max_page = max_reads[task.id] : max_page = 0
      total_pages = task.book.total_pages
      self.cal_percentage(tasks_percentage, max_page, total_pages)
    end
    return tasks_percentage
  end

  # タスク個別の進捗パーセンテージ(TaskShowページ)
  def self.task_percentage(task)
    task_percentage = []
    max_page = task.reads.select(:up_to_page).maximum(:up_to_page) || 0
    total_pages = task.book.total_pages
    self.cal_percentage(task_percentage, max_page, total_pages)
    return task_percentage
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[show edit update destroy]

  def today
    tasks = current_user.tasks.includes(:book).all
    @tasks = Task.tasks_in_progress(tasks)
    @tasks.each_with_index do |task, i|
      val = "@target#{i}"
      eval("#{val} = Task.today_data(task)")
    end
  end

  def index
    @tasks = current_user.tasks.includes(:book).all.order(finished_on: :desc)
    @tasks_percentage = Task.tasks_percentage(@tasks)
    @reads = current_user.reads
    @month_data = Read.month_data(current_user)
  end

  def show
    @task_percentage = Task.task_percentage(@task)
    @reads = @task.reads.all.order(up_to_page: :desc)
    @reads_percentage = Read.reads_percentage(@reads, @task)
  end

  def new
    @book = Book.find_by(id: params[:book_id])
    @task = Task.new
  end

  def create
    @book = Book.find_by(id: params[:book_id])
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to today_tasks_path, notice: "目標を登録しました"
    else
      flash.now[:alert] = "目標の登録に失敗しました"
      render :new
    end
  end

  def edit
    @book = @task.book
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: "目標を更新しました"
    else
      flash.now[:alert] = "目標の更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @task.destroy!
    redirect_to tasks_path, alert: "目標を削除しました"
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:started_on, :finished_on, :user_id).merge(book_id: params[:book_id])
  end
end

app/views/tasks/_calendar.html.erb
<%= month_calendar(events: reads) do |date, reads| %>
  <%= date.day %>
  <% reads.each do |read| %>
    <div class=""></div>
  <% end %>
<% end %>

app/views/tasks/_form.html.erb
<div class="TaskForm">
  <div class="c-container">
    <%= render 'shared/page_bar', var: "", text: "開始日と終了日を設定" %>

    <div class="TaskForm__wrapper">
      <section class="TaskForm__book">
        <div class="TaskForm__title"><%= book.title %></div>
        <div class="TaskForm__book-image">
          <% if controller.action_name == 'new' %>
            <%= render 'books/book_image', image_link: book.image_link %>
          <% elsif controller.action_name == 'edit' %>
            <%= render 'books/book_image', image_link: task.book.image_link %>
          <% end %>
        </div>
      </section>

      <section class="TaskForm__task">
        <%= form_with model: task, local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>
          <%= hidden_field_tag :book_id, book.id %>
          <div class="TaskForm__form">
            <%= f.label :started_on %>
            <%= f.date_field :started_on, id: "started_on" %>
          </div>
          <div class="TaskForm__form">
            <%= f.label :finished_on %>
            <%= f.date_field :finished_on, id: "finished_on" %>
          </div>

          <div class="TaskForm__result">
            <div class="TaskForm__result-title">
              <i class="fas fa-flag-checkered"></i>
              <span>目標</span>
            </div>
            <div class="TaskForm__result-content">
              <dl>
                <i class="fas fa-check"></i>
                <dt><span>読み終わる日数</span></dt>
                <dd><span id="days"></span></dd>
              </dl>
              <dl>
                <i class="fas fa-check"></i>
                <dt><span>1日のページ数</span></dt>
                <dd><span id="page", data-page-id="<%= book.total_pages %>"></span></dd>
              </dl>
            </div>
          </div>

          <div class="TaskForm__submit">
            <%= f.submit button_value %>
          </div>
        <% end %>
      </section>
    </div>
  </div>
</div>

app/views/tasks/_history_table.html.erb
<div class="TaskHistoryTable">
  <div class="TaskHistoryTable__title"><%= month_name %>の読書量</div>
  <table>
    <tbody>
      <tr>
        <td class="number"><%= month_data[:read_pages] %></td>
        <td class="unit">ページ</td>
      </tr>
      <tr>
        <td class="number"><%= month_data[:read_book] %></td>
        <td class="unit">冊</td>
      </tr>
      <tr>
        <td class="number"><%= month_data[:day_pages] %></td>
        <td class="unit">ページ/日</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/tasks/_percentage.html.erb
<div class="progress" style="height: 26px; width: 400px;">
  <div class="progress-bar progress-bar-striped"
    role="progressbar"
    style="width:<%= percentage %>%; background-color:blue;"
    aria-valuenow="<%= percentage %>"
    aria-valuemin="0"
    aria-valuemax="100">
    <%= percentage %>%
  </div>
</div>

app/views/tasks/_task_nav.html.erb
<nav class="TaskNav">
  <ul>
    <li class="--today<%= ' --now' if controller.action_name == 'today' %>">
      <%= link_to(today_tasks_path) do %>
        <span class="en">Today</span>
        <span class="ja">今日の目標</span>
      <% end %>
    </li>
    <li class="--all<%= ' --now' if controller.action_name == 'index' %>">
      <%= link_to(tasks_path) do %>
        <span class="en">All</span>
        <span class="ja">タスク一覧</span>
      <% end %>
    </li>
  </ul>
</nav>

app/views/tasks/edit.html.erb
<div class="TaskEdit">
  <%= render 'shared/page_top', main: "Task", sub: "目標の編集" %>
  <div class="c-container">
      <div class="Breadcrumbs">
        <%= link_to 'TOP', '/' %>
        <span class="--arrow">></span>
        <%= link_to 'タスクの詳細', @task, class: "Breadcrumbs__item" %>
        <span class="--arrow">></span>
        <span class="--now">タスクの編集</span>
      </div>
    </div>

  <%= render 'form', task: @task, book: @book, button_value: "更新" %>
</div>

app/views/tasks/index.html.erb
<div class="TaskIndex">
  <%= render 'shared/page_top', main: "All", sub: "目標の一覧" %>
  <div class="c-container">
    <div class="Breadcrumbs">
      <%= link_to 'TOP', '/' %>
      <span class="--arrow">></span>
      <span class="--now">目標の一覧</span>
    </div>
  </div>

  <div class="c-container">
    <%= render 'task_nav' %>

    <div class="TaskIndex__wrapper  --first">
      <div class="TaskIndex__calendar">
        <h2>HISTORY</h2>
        <div id="calendar">
          <%= render "calendar", reads: @reads %>
        </div>
      </div>
      <div class="TaskIndex__table">
        <%= render "history_table", month_data: @month_data[:this_month], month_name: "今月" %>
        <%= render "history_table", month_data: @month_data[:last_month], month_name: "先月" %>
      </div>
    </div>

    <div class="TaskIndex__wrapper --second">
      <% @tasks.zip(@tasks_percentage) do |task, data| %>
        <div class="TaskIndexCard">
          <%= link_to(task) do %>
            <div class="TaskIndexCard__title"><%= task.book.title %></div>
            <div class="TaskIndexCard__wrapper">
              <div class="TaskIndexCard__content">
                <div class="TaskIndexCard__data">
                  <div class="TaskIndexCard__book-image">
                    <%= render 'books/book_image', image_link: task.book.image_link %>
                  </div>
                  <div class="TaskIndexCard__finished-on">
                    <span class="label">目標日</span>
                    <span><%= task.finished_on.strftime("%-m月%-d日") %></span>
                  </div>
                </div>
              </div>
              <%= pie_chart data, width: "10rem", height: "10rem", library: {title: {text: "#{data[:read]}%", style:{fontSize: "1.5em"} }} %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/index.js.erb
$("#calendar").html("<%= escape_javascript render("calendar", reads: @reads) %>")

app/views/tasks/new.html.erb
<div class="TaskNew">
  <%= render 'shared/page_top', main: "Task", sub: "目標を設定しましょう。" %>
  <%= render 'shared/breadcrumbs' %>

  <%= render 'form', task: @task, book: @book, button_value: "登録" %>
</div>

app/views/tasks/show.html.erb
<div class="TaskShow">
  <%= render 'shared/page_top', main: "Show", sub: "目標の詳細" %>
  <div class="c-container">
    <div class="Breadcrumbs">
      <%= link_to 'TOP', '/' %>
      <span class="--arrow">></span>
      <%= link_to '目標の一覧', tasks_path %>
      <span class="--arrow">></span>
      <span class="--now">詳細</span>
    </div>
  </div>

  <div class="c-container">
    <div class="TaskShow__wrapper">
      <div class="TaskShow__container">
        <div class="TaskShow__content">
          <%= pie_chart @task_percentage[0], width: "20em", height: "20em", library: {title: {text: "#{@task_percentage[0][:read]}%", style:{fontSize: "2em"} }} %>
          <div class="TaskShow__data">
            <div class="TaskShow__title"><%= @task.book.title %></div>
            <div class="TaskShow__item">
              <div class="TaskShow__book-image">
                <%= render 'books/book_image', image_link: @task.book.image_link %>
              </div>
              <table class="--task">
                <tbody>
                  <tr class="--task">
                    <td class="--label">開始日</td>
                    <td class="--data"><%= @task.started_on %></td>
                  </tr>
                  <tr class="--task">
                    <td class="--label">終了日</td>
                    <td class="--data"><%= @task.finished_on %></td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="TaskShow__link">
              <%= link_to "編集", edit_task_path(@task) %>
              <%= link_to "削除", @task, class: "--delete", method: :delete, data: { confirm: "目標を削除しますか?" } %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="TaskShow__wrapper">
      <div class="TaskShow__container">
        <%= render "reads/index", task: @task, reads: @reads, reads_percentage: @reads_percentage %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/today.html.erb
<div class="TaskToday">
  <%= render 'shared/page_top', main: "Today", sub: "今日の目標" %>
  <div class="c-container">
    <div class="Breadcrumbs">
      <%= link_to 'TOP', '/' %>
      <span class="--arrow">></span>
      <span class="--now">今日の目標</span>
    </div>

    <%= render 'task_nav' %>
    <div class="TaskToday__wrapper">
      <% @tasks.each_with_index do |task, i| %>
        <% val = "@target#{i}" %>
        <%= link_to task, class: "TaskToday__link" do %>

          <div class="TaskToday__card">
            <div class="TaskToday__border --<%= eval("#{val}[:status][:color]") %>"></div>
            <div class="TaskToday__item">
              <div class="TaskToday__status --<%= eval("#{val}[:status][:color]") %>">
                <span><%= eval("#{val}[:status][:status]") %></span>
              </div>
              <div class="TaskToday__title"><%= task.book.title %></div>
              <div class="TaskToday__content">
                <div class="TaskToday__book-image">
                  <%= render 'books/book_image', image_link: task.book.image_link %>
                </div>

                <div class="TaskToday__goal">
                  <dl>
                    <dt>今日の目標</dt>
                    <dd>p.<%= eval("#{val}[:today_goal_page]") %>まで</dd>
                  </dl>
                  <div class="TaskToday__read">
                    <% eval("#{val}[:status_week]").each do |date, val| %>
                      <span class="--circle <%= val %>">
                        <object>
                          <%= link_to new_task_read_path(task_id: task.id, read_on: date) do %>
                            <span class="--date <%= val %>"><%= date %></span>
                          <% end %>
                        </object>
                      </span>
                    <% end %>
                  </div>
                </div>

              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>