config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "home#index"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:new, :create]
  get '/books', to: 'books#search'

  resources :tasks do
    collection do
      get 'today'
    end

    resources :reads, only: [:new, :create, :destroy]
  end
end

app/views/shared/_breadcrumbs.html.erb
<div class="c-container">
  <div class="Breadcrumbs">
    <%= link_to 'TOP', '/' %>
    <span class="--arrow">></span>
    <span class="<%= '--now' if controller_name == 'books' %>">本の登録</span>
    <span class="--arrow">></span>
    <span class="<%= '--now' if controller_name == 'tasks' %>">目標の設定</span>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><span style="color: red;"><%= msg %></span></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="Footer">
  <div class="c-container">
    <div class="Footer__wrapper">
      <div class="Footer__item">
        <i class="fas fa-arrow-circle-right"></i>
        <%= link_to "トップ", "/" %>
      </div>
      <div class="Footer__item">
        <p>&copy; 2021 BookDaily</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="Header">
  <div class="Header__logo">
    <%= link_to image_tag('title.png'), "/" %>
  </div>

  <nav>
    <%# unless current_page?(root_path) %>
      <div class="Header__search">
        <%= render 'books/search_form' %>
      </div>
    <%# end %>
    <ul id="js-Header__list">
      <% if user_signed_in? %>
        <div class="Header__border"></div>
        <li>
          <%= link_to(today_tasks_path) do %>
            <i class="far fa-bookmark"></i>
            <span class="Header__text">TASK</span>
          <% end %>
        </li>
        <div class="Header__border"></div>
        <li>
          <%= link_to(edit_user_registration_path) do %>
            <i class="far fa-user"></i>
            <span class="Header__text">ACCOUNT</span>
          <% end %>
        </li>
        <div id="js-Header__border"></div>
      <% else %>
        <div class="Header__border"></div>
        <li>
          <%= link_to(new_user_session_path) do %>
            <i class="far fa-user"></i>
            <span class="Header__text">LOGIN</span>
          <% end %>
        </li>
        <div id="js-Header__border"></div>
      <% end %>
    </ul>

    <!-- tab以下の場合 -->
    <button class="Header__toggle" id="js-Header__toggle"></button>
    <div class="Header__wrapper">
      <div class="Header__content" id="js-Header__content"></div>
    </div>
  </nav>
</div>

app/views/shared/_page_bar.html.erb
<section class="PageBar">
  <h3><%= var %><%= text %></h3>
</section>

app/views/shared/_page_top.html.erb
<section class="PageTop">
  <h1>
    <span class="--main"><%= main %></span>
    <small class="--sub"><%= sub %></small>
  </h1>
</section>