config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "home#index"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:new, :create]
  get '/books', to: 'books#search'

  resources :tasks do
    collection do
      get 'today'
    end

    resources :reads, only: [:new, :create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :tasks, dependent: :destroy

  # バリデーション
  validates :title, presence: true
  validates :total_pages, presence: true, numericality: true
  validates :google_id, presence: true, uniqueness: true

  # GoogleBooksAPIでの検索結果を配列に整形
  def self.results_array(results_json)
    results = []

    results_json["items"].each do |result|
      google_id = result.dig("id")
      info = result.dig("volumeInfo")
      title = info.dig("title")
      authors = info.dig("authors")
      image_link = info.dig("imageLinks", "smallThumbnail")
      total_pages = info.dig("pageCount")

      # 総ページ数のデータがない書籍は検索結果に表示しない
      if total_pages.blank?
        next
      end

      # 著者が複数名の表記
      if authors
        author = authors.join(', ')
      end

      results.push(
        {
          google_id: google_id,
          title: title,
          author: author,
          image_link: image_link,
          total_pages: total_pages
        }
      )
    end
    return results
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include GoogleBooksApi
  before_action :authenticate_user!, except: [:search, :new]

  def search
    if params[:keyword].present?
      url= url_from_keyword(params[:keyword])
      results_json = get_json_from_url(url)
      @results = Book.results_array(results_json)
    end
  end

  def new
    @book = Book.find_or_initialize_by(google_id: params[:google_id])

    unless @book.persisted?
      @book = Book.new(book_data)
    end
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to new_task_path(book_id: @book.id)
    else
      flash[:alert] = "本の登録に失敗しました"
      render :new
    end
  end

  private

  def book_data
    {
      google_id: params[:google_id],
      title: params[:title],
      author: params[:author],
      image_link: params[:image_link],
      total_pages: params[:total_pages],
    }
  end

  def book_params
    params.require(:book).permit(:google_id, :title, :author, :image_link, :total_pages)
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_image(image_link)
    if image_link.present?
      image_link
    else
      'book.png'
    end
  end
end

app/views/books/_book_image.html.erb
<div class="BookImage">
  <%= image_tag book_image(image_link) %>
</div>

app/views/books/_modal_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">

    <div class="BookNew">
      <div class="BookNew__close">
        <button type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="BookNew__title">書籍の新規登録</div>
        <div class="BookNew__content">
          <div class="BookNew__book-image">
            <%= render 'book_image', image_link: book.image_link %>
          </div>
          <div class="BookNew__data">
            <dl>
              <dt>タイトル</dt>
              <dd><%= book.title %></dd>
            </dl>
            <dl>
              <dt>著者</dt>
              <dd><%= book.author %></dd>
            </dl>
            <dl>
              <dt>ページ数</dt>
              <dd><%= book.total_pages %>ページ</dd>
            </dl>
          </div>
        </div>

        <% if book.persisted? %>
          <!-- 登録がある場合のリンク -->
          <div class="BookNew__submit">
            <%= link_to(controller: :tasks, action: :new, book_id: book.id) do %>
              <button>登録</button>
            <% end %>
          </div>
        <% else %>
          <!-- 登録がない場合のフォーム -->
          <%= form_with model: book, remote: true do |f| %>
            <%= render 'shared/error_messages', model: f.object %>
            <%= f.hidden_field :google_id, value:book.google_id %>
            <%= f.hidden_field :title, value:book.title %>
            <%= f.hidden_field :author, value:book.author %>
            <%= f.hidden_field :image_link, value:book.image_link %>
            <%= f.hidden_field :total_pages, value:book.total_pages %>
            <div class="BookNew__submit">
              <%= f.submit "登録" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/_search_form.html.erb
<div class="SearchForm">
  <%= form_with url: books_path, id: 'js-SearchForm', method: :get, local: true do |f| %>
    <%= f.text_field :keyword, id: :keyword, placeholder: "タイトル、著者名" %>
    <%= f.button type: "submit" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>

app/views/books/new.js.erb
$("#book-new-modal").html("<%= escape_javascript(render 'modal_new', book: @book) %>")
$("#book-new-modal").modal("show")

app/views/books/search.html.erb
<!-- トップ-->
<%= render 'shared/page_top', main: "Books", sub: "読みたい本を選んでください。" %>
<%= render 'shared/breadcrumbs' %>

<!-- 検索結果 -->
<div class="c-container">
  <%= render 'shared/page_bar', var: params[:keyword], text: " の検索結果" %>

  <section class="SearchList">
    <ul>
      <% if @results %>
        <% @results.each do |result| %>
          <li>
            <%= link_to(controller: :books, action: :new, google_id: result[:google_id], title: result[:title], author: result[:author], image_link: result[:image_link], total_pages: result[:total_pages], remote: true) do %>
              <div class="SearchList__item">
                <div class="SearchList__book-image">
                  <%= render 'book_image', image_link: result[:image_link] %>
                </div>
                <span class="--title"><%= result[:title] %></span>
                <span class="--author"><%= result[:author] %></span>
                <dl>
                  <dt>ページ数</dt>
                  <dd><%= result[:total_pages] %></dd>
                </dl>
                <div class="book-submit">
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
      <% else %>
        <p>検索結果がありません。<br>他のキーワードで検索してみてください。</p>
      <% end %>
    </ul>
  </section>
</div>

<!-- 新規登録用モーダル -->
<div id="book-new-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>